version: 4.8.0/{branch}-{build}
image:
- Visual Studio 2022
- Ubuntu
# - macOS
configuration: Release
platform: Any CPU

init:
- sh: >-
    sudo apt update && sudo apt upgrade --yes

    sudo apt install --yes build-essential autoconf libmpfr-dev libgmp3-dev libmpc-dev

    wget http://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.gz

    tar -xf gcc-14.2.0.tar.gz

    cd gcc-14.2.0

    ./configure -v --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --prefix=/usr/local/gcc-14.2.0 --enable-checking=release --enable-languages=c,c++ --disable-multilib --program-suffix=-14.2.0

    make

    sudo make install

    cd ../

    rm -rf gcc-14.2.0

    git clone https://github.com/chriskohlhoff/asio.git

    cd asio/asio/

    ./autogen.sh

    ./configure

    make

    sudo make install

    cd ../../

    rm -rf asio/

    git clone https://github.com/catchorg/Catch2.git

    cd Catch2

    cmake -Bbuild -H. -DBUILD_TESTING=OFF

    sudo cmake --build build/ --target install

    cd ../

    rm -rf Catch2/

- cmd: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_x64'
install:
- git submodule update --init --recursive
- mkdir build
- cd build
build_script:
- sh: >-
    cmake ..

    make
- cmd: >-
    cmake -G "Visual Studio 17 2022" -DBUILD_SSL=NO -DBUILD_TESTS=YES ..

    cmake --build . --target ALL_BUILD --config Release
test_script:
- ctest
deploy: off
