version: 4.8.0/{branch}-{build}
image:
- Visual Studio 2022
- Ubuntu
# - macOS
configuration: Release
platform: Any CPU

init:
- sh: >-
    sudo apt update && sudo apt upgrade --yes

    sudo apt install --yes build-essential autoconf

    sudo apt install --yes g++-14

    git clone https://github.com/chriskohlhoff/asio.git

    cd asio/asio/

    ./autogen.sh

    ./configure

    make

    sudo make install

    cd ../../

    rm -rf asio/

    git clone https://github.com/catchorg/Catch2.git

    cd Catch2

    cmake -Bbuild -H. -DBUILD_TESTING=OFF

    sudo cmake --build build/ --target install

    cd ../

    rm -rf Catch2/

- cmd: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_x64'
install:
- git submodule update --init --recursive
- mkdir build
- cd build
build_script:
- sh: >-
    cmake ..

    make
- cmd: >-
    cmake -G "Visual Studio 17 2022" -DBUILD_SSL=NO -DBUILD_TESTS=YES ..

    cmake --build . --target ALL_BUILD --config Release
test_script:
- ctest
deploy: off
